# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'intens36-Lukyanov' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire', '~> 4.5'
pod 'SwiftyJSON', '4.0.0-alpha.1'

  # Pods for intens36-Lukyanov



  target 'intens36-LukyanovTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
